# File: .github/workflows/update_blocklist.yml
name: ULTIMATE TRUE GOAT BLOCK LIST - Updater

on:
  schedule:
    # Runs automatically every 6 hours to keep the list fresh.
    - cron: "0 */6 * * *"
  workflow_dispatch:
    # Allows you to run this workflow manually from the GitHub Actions tab.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Blocklist Generator Script
        run: python generate_list.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add all generated files to the staging area
          git add ultimate_brave_blocklist.txt README.md fetch_errors.log
          
          # Check if there are any changes to commit
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update ULTIMATE TRUE GOAT BLOCK LIST - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "Successfully committed and pushed updates."
          else
            echo "No changes to commit. The blocklist is already up to date."
          fi
