name: Update Robust Block List Pro

on:
  schedule:
    - cron: '0 5 * * *'   # daily build
    - cron: '0 0 * * 0'   # weekly validate-sources
  workflow_dispatch:

# allow pushing with GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 5 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # let checkout persist credentials so plain `git push` works
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tenacity

      - name: Run List Generation
        run: |
          python generate_list.py 2>&1 | tee script.log

      - name: Commit and Push Changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add robust_block_list_pro.txt robust_block_list_pro_hosts.txt robust_block_list_pro_domains.txt filtered_secrets.log || true
          if ! git diff --cached --quiet; then
            git commit -m "Update Robust Block List Pro with multiple formats"
            # pull (read) is fine with the checkout token
            git pull --rebase origin main || true
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: script.log

  validate-sources:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * 0'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Validate URLs
        run: python validate_urls.py 2>&1 | tee validate.log

      - name: Upload Validation Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validate-logs
          path: validate.log
