name: Update Block Lists

on:
  schedule:
    - cron: "0 0 * * *"   # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests

      - name: Run generator
        run: python generate_list.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add robust_block_list_pro_combined.txt
          git add robust_block_list_ios_lite.txt
          git add CHANGELOG.md
          git add fetch_errors.log
          git add README.md
          git commit -m "chore: update blocklists ($(date -u +%Y-%m-%d))" || echo "No changes to commit"
          git push
