name: Update Block Lists

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run generator
        run: python generate_list.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add robust_block_list_pro_combined.txt robust_block_list_ios_lite.txt README.md fetch_errors.log
          git commit -m "Update combined block list & metadata - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes"
          git push