name: Update Robust Block List Pro

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the Python Script
        run: python generate_list.py

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add robust_block_list_pro.txt
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update Robust Block List Pro"
            git push https://x-access-token:${PAT_TOKEN}@github.com/avion121/robust-block-list-pro.git HEAD:main
          else
            echo "No changes to commit"
