name: Generate Robust Block Lists

on:
  schedule:
    - cron: "0 3 * * *"   # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate lists
        run: python generate_list.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add robust_block_list_pro_balanced.txt robust_block_list_pro_monster.txt fetch_meta.json fetch_errors.log
          git commit -m "Update Robust Block Lists - $(date -u +%Y-%m-%d)" || echo "No changes to commit"
          git push
